rootAction:
  key: q7wbgb8a
  conditionActions:
    falseAction:
      key: jdzwl9bu
      action:
        key: xiyxveas
    trueActions:
      - condition:
          variable:
            source: LOCAL_STATE
            baseVariable:
              localState:
                fieldIdentifier:
                  name: selectedHobbies
                  key: 2dova
                stateVariableType: WIDGET_CLASS_STATE
            operations:
              - listContains:
                  element:
                    source: FIRESTORE_REQUEST
                    baseVariable:
                      firestore: {}
                    operations:
                      - accessDocumentField:
                          documentProperty: REFERENCE
                    nodeKeyRef:
                      key: Wrap_wmbwcj14
            nodeKeyRef:
              key: Scaffold_q6vv4dxg
        trueAction:
          key: lrcb7c5a
          action:
            key: fbaa5rtf
    hasMultiConditions: false
trigger:
  triggerType: ON_TAP