rootAction:
  key: xmu8fum5
  conditionActions:
    falseAction:
      key: 0u40swsn
      action:
        key: i5quo0q8
    trueActions:
      - condition:
          variable:
            source: LOCAL_STATE
            baseVariable:
              localState:
                fieldIdentifier:
                  name: selectedHobbies
                  key: 2dova
                stateVariableType: WIDGET_CLASS_STATE
            operations:
              - listContains:
                  element:
                    source: FIRESTORE_REQUEST
                    baseVariable:
                      firestore: {}
                    operations:
                      - accessDocumentField:
                          documentProperty: REFERENCE
                    nodeKeyRef:
                      key: Row_njcnqp6o
            nodeKeyRef:
              key: Scaffold_1tfu6pmt
        trueAction:
          key: dlzgugav
          action:
            key: mh5vl95x
    hasMultiConditions: false
trigger:
  triggerType: ON_TAP